### ISSUE TITLE
`Bad argument` when trying to start server.

### ISSUE THREAD

**Issue by usandfriends** [Quramy/electron-connect#11]
Using `node.js` version `v4.1.1`, I get the following error when trying to start the server:

```
internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at Object.exports.spawn (child_process.js:339:9)
    at EventEmitter.ProcessManager.spawn (/Users/usandfriends/Documents/GitHub/electron-test/node_modules/electron-connect/lib/server.js:28:28)
    at EventEmitter.<anonymous> (/Users/usandfriends/Documents/GitHub/electron-test/node_modules/electron-connect/lib/server.js:47:10)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1257:10)
    at doNTCallback1 (node.js:418:9)
```

**Comment by usandfriends** [comment]
Wow, I just found this again after trying to start up my old project. Any ideas @Quramy?

**Comment by usandfriends** [comment]
^ Sorry about the mess. I just created a [pull request](https://github.com/Quramy/electron-connect/pull/15).
