### ISSUE TITLE
Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by mitchhentges** [Quramy/electron-connect#29]
On first start, and whenever a change occurs, I see the following stacktrace. Note that it's `electron-connect`'s `socket.on('message')` callback that is causing this.

`electron-prebuilt`: `0.37.2` (though it was also occurring with `0.36.11`)
`electron-connect`: `0.3.7`

```
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/home/mitch/dev/james/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/home/mitch/dev/james/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/rpc-server.js:337:31)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (/home/mitch/dev/james/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at ObjectsRegistry.get (/home/mitch/dev/james/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/home/mitch/dev/james/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/rpc-server.js:337:31)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (/home/mitch/dev/james/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/home/mitch/dev/james/node_modules/electron-prebuilt/dist/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.descriptor.get [as webContents] (/home/mitch/dev/james/node_modules/electron-prebuilt/dist/resources/atom.asar/renderer/api/remote.js:118:16)
    at EventEmitter.<anonymous> (/home/mitch/dev/james/node_modules/electron-connect/lib/client.js:108:21)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/home/mitch/dev/james/node_modules/electron-connect/lib/client.js:64:16)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/home/mitch/dev/james/node_modules/ws/lib/WebSocket.js:816:10)
    at /home/mitch/dev/james/node_modules/ws/lib/Receiver.js:477:18

**Comment by mitchhentges** [comment]
Note: This error only occurs when `client.create()` is called from the `RendererProcess` (according to https://github.com/Quramy/electron-connect#client)

**Comment by mitchhentges** [comment]
Ah, I've fixed a variant of this before: https://github.com/james-proxy/james/pull/161/commits/f39005b95d68ab73724c7c0dd0acf0f2631ff0e6
It's because `getCurrentWindow()` is run once, then that result is cached by `electron-connect`. 

So, `remote.getCurrentWindow()` has to be executed each time that the window is wanted. Perhaps an electron bug?

**Comment by mitchhentges** [comment]
Good news everyone, not a bug with `electron-connect`! Rather, `electron` itself has a bug somewhere: https://github.com/atom/electron/issues/4733
