### ISSUE TITLE
Error: spawn electron ENOENT when running gulp serve

### ISSUE THREAD

**Issue by divramod** [Quramy/electron-connect#68]
Hey, i get the following error when running gulp serve:

```
[22:28:13] Starting 'serve'...
[22:28:13] Finished 'serve' after 4.6 ms
[2016-11-15T21:28:13.505Z] [electron-connect] [server] started electron process: undefined
[2016-11-15T21:28:13.506Z] [electron-connect] [server] created and listening on 30080
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn electron ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:1003:3
```

i am running ubuntu, node v5.4.0, gulp 3.9.1, npm 4.0.1

can someone help me out here?

**Comment by lcaprini** [comment]
+1 Same error...any idea?

**Comment by divramod** [comment]
i removed electron from node_modules and installed it globally. now it is running

**Comment by MarioHofer** [comment]
I uninstalled [electron-prebuilt](https://www.npmjs.com/package/electron-prebuilt) to make it work.

**Comment by shikisokuzeku** [comment]
I got same error. 
I removed all from node_modules and reinstalled.

```
$ rm -rf node_modules
$ npm install
```
Althrough I couldn't find direct cause, work correctly now.

**Comment by uriylla** [comment]
I've been two days stuck with this..
