### ISSUE TITLE
Connection error (ECONNREFUSED)

### ISSUE THREAD

**Issue by leonard-thieu** [Quramy/electron-connect#74]
I get the following 2 errors when the client tries to connect:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: connect ECONNREFUSED 127.0.0.1:30080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketCloseListener (_http_client.js:285:23)
    at emitOne (events.js:101:20)
    at Socket.emit (eventsjs:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12) 
```
Operating system: Windows 7
Electron: 1.6.7

This happens if I try to connect in the renderer process too with the exceptions being reported in the console.

Repro project available at https://github.com/leonard-thieu/electron-connect-econnrefused

Related to #23.

**Comment by mreis1** [comment]
+1  Same issue here

**Comment by alejandrocena** [comment]
+1

**Comment by ssreekanth** [comment]
@leonard-thieu See pull request https://github.com/leonard-thieu/electron-connect-econnrefused/issues/1 for the fix.

Closing this issue.
